project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"

preserve_hierarchy: true

files:
    - source: patches/src/main/resources/addresources/values/music/strings.xml
      translation: patches/src/main/resources/addresources/values-%android_code%/music/strings.xml
      dest: '/Patches/music.xml'
      skip_untranslated_strings: true

    - source: patches/src/main/resources/addresources/values/youtube/strings.xml
      translation: patches/src/main/resources/addresources/values-%android_code%/youtube/strings.xml
      dest: '/Patches/youtube.xml'
      skip_untranslated_strings: true

    - source: patches/src/main/resources/addresources/values/shared/strings.xml
      translation: patches/src/main/resources/addresources/values-%android_code%/shared/strings.xml
      dest: '/Patches/shared.xml'
      skip_untranslated_strings: true

    - source: patches/src/main/resources/addresources/values/shared-youtube/strings.xml
      translation: patches/src/main/resources/addresources/values-%android_code%/shared-youtube/strings.xml
      dest: '/Patches/shared-youtube.xml'
      skip_untranslated_strings: true
